CUDA_VERSION=12.4.1
UBUNTU_VERSION=22.04
VLLM_VERSION=0.19.1
PYTORCH_CU_VERSION=118

docker build -t vllm:${VLLM_VERSION}-cuda-${CUDA_VERSION}-ubuntu${UBUNTU_VERSION}-pytorch-cu${PYTORCH_CU_VERSION} \
  --build-arg CUDA_VERSION=${CUDA_VERSION} \
  --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
  --build-arg VLLM_VERSION=${VLLM_VERSION} \
  --build-arg PYTORCH_CU_VERSION=${PYTORCH_CU_VERSION} \
  .
